// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUaTciSzy0-lJh0wujeNufQoDJMP22zjg',
    appId: '1:369140535049:web:f0d2d42ff7df96106c4dd8',
    messagingSenderId: '369140535049',
    projectId: 'shop-app-746e9',
    authDomain: 'shop-app-746e9.firebaseapp.com',
    storageBucket: 'shop-app-746e9.appspot.com',
    measurementId: 'G-13WS73DM1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsilgAK2eDqr0JckPR6ZTOs9ksefszfC0',
    appId: '1:369140535049:android:e86fc73f91b9425d6c4dd8',
    messagingSenderId: '369140535049',
    projectId: 'shop-app-746e9',
    storageBucket: 'shop-app-746e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8EZ5yd05Lj-R3ct2puju-amApp04e-U',
    appId: '1:369140535049:ios:dbcb94f305729b9c6c4dd8',
    messagingSenderId: '369140535049',
    projectId: 'shop-app-746e9',
    storageBucket: 'shop-app-746e9.appspot.com',
    iosBundleId: 'com.example.connectxTaskShopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8EZ5yd05Lj-R3ct2puju-amApp04e-U',
    appId: '1:369140535049:ios:dbcb94f305729b9c6c4dd8',
    messagingSenderId: '369140535049',
    projectId: 'shop-app-746e9',
    storageBucket: 'shop-app-746e9.appspot.com',
    iosBundleId: 'com.example.connectxTaskShopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUaTciSzy0-lJh0wujeNufQoDJMP22zjg',
    appId: '1:369140535049:web:4793dd4f9e9b95256c4dd8',
    messagingSenderId: '369140535049',
    projectId: 'shop-app-746e9',
    authDomain: 'shop-app-746e9.firebaseapp.com',
    storageBucket: 'shop-app-746e9.appspot.com',
    measurementId: 'G-7BVCP8LCSW',
  );
}
